# --------------- Apariencia ---------------
[window]
opacity = 1.0              # Equivalente a `window_background_opacity`
decorations = "none"
padding = { x = 0, y = 0 }
dynamic_padding = false
dynamic_title = true

[scrolling]
history = 10000 # Buffer de scroll

# --------------- Colores ---------------
[colors.primary]
foreground = "#dcd7ba"
background = "#000000"

[colors.cursor]
text = "#c8c093"
cursor = "#c8c093"

[colors.selection]
text = "#c8c093"
background = "#2d4f67"

[colors.normal]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"

[colors.bright]
black = "#727169"
red = "#e82424"
green = "#98bb6c"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#dcd7ba"

# --------------- Fuente ---------------
[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[env]
TERM = "xterm-256color" # Mejor compatibilidad

[debug]
log_level = "Warn"
